package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TblAcyearMaster generated by hbm2java
 */
public class TblAcyearMaster implements java.io.Serializable {

	private String acyearId;
	private String acyearName;
	private String acyearText;
	private Date acyearFromdate;
	private Date acyearTodate;
	private String acyearCurrentyear;

	public TblAcyearMaster() {
	}

	public TblAcyearMaster(String acyearId) {
		this.acyearId = acyearId;
	}

	public TblAcyearMaster(String acyearId, String acyearName,
			String acyearText, Date acyearFromdate, Date acyearTodate,
			String acyearCurrentyear) {
		this.acyearId = acyearId;
		this.acyearName = acyearName;
		this.acyearText = acyearText;
		this.acyearFromdate = acyearFromdate;
		this.acyearTodate = acyearTodate;
		this.acyearCurrentyear = acyearCurrentyear;
	}

	public String getAcyearId() {
		return this.acyearId;
	}

	public void setAcyearId(String acyearId) {
		this.acyearId = acyearId;
	}

	public String getAcyearName() {
		return this.acyearName;
	}

	public void setAcyearName(String acyearName) {
		this.acyearName = acyearName;
	}

	public String getAcyearText() {
		return this.acyearText;
	}

	public void setAcyearText(String acyearText) {
		this.acyearText = acyearText;
	}

	public Date getAcyearFromdate() {
		return this.acyearFromdate;
	}

	public void setAcyearFromdate(Date acyearFromdate) {
		this.acyearFromdate = acyearFromdate;
	}

	public Date getAcyearTodate() {
		return this.acyearTodate;
	}

	public void setAcyearTodate(Date acyearTodate) {
		this.acyearTodate = acyearTodate;
	}

	public String getAcyearCurrentyear() {
		return this.acyearCurrentyear;
	}

	public void setAcyearCurrentyear(String acyearCurrentyear) {
		this.acyearCurrentyear = acyearCurrentyear;
	}

}
