package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblBillreferencesDetails generated by hbm2java
 */
public class TblBillreferencesDetails implements java.io.Serializable {

	private Integer billrefId;
	private String billNos;
	private String referenceId;
	private String billrefValue;

	public TblBillreferencesDetails() {
	}

	public TblBillreferencesDetails(String billNos, String referenceId,
			String billrefValue) {
		this.billNos = billNos;
		this.referenceId = referenceId;
		this.billrefValue = billrefValue;
	}

	public Integer getBillrefId() {
		return this.billrefId;
	}

	public void setBillrefId(Integer billrefId) {
		this.billrefId = billrefId;
	}

	public String getBillNos() {
		return this.billNos;
	}

	public void setBillNos(String billNos) {
		this.billNos = billNos;
	}

	public String getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

	public String getBillrefValue() {
		return this.billrefValue;
	}

	public void setBillrefValue(String billrefValue) {
		this.billrefValue = billrefValue;
	}

}
