package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblBillparticularsDetails generated by hbm2java
 */
public class TblBillparticularsDetails implements java.io.Serializable {

	private Integer billpartiId;
	private String billNos;
	private String particularsId;
	private Double billpartiAmount;
	private Integer billpartiQuantity;
	private Double billpartiTotalamt;

	public TblBillparticularsDetails() {
	}

	public TblBillparticularsDetails(String billNos, String particularsId,
			Double billpartiAmount, Integer billpartiQuantity,
			Double billpartiTotalamt) {
		this.billNos = billNos;
		this.particularsId = particularsId;
		this.billpartiAmount = billpartiAmount;
		this.billpartiQuantity = billpartiQuantity;
		this.billpartiTotalamt = billpartiTotalamt;
	}

	public Integer getBillpartiId() {
		return this.billpartiId;
	}

	public void setBillpartiId(Integer billpartiId) {
		this.billpartiId = billpartiId;
	}

	public String getBillNos() {
		return this.billNos;
	}

	public void setBillNos(String billNos) {
		this.billNos = billNos;
	}

	public String getParticularsId() {
		return this.particularsId;
	}

	public void setParticularsId(String particularsId) {
		this.particularsId = particularsId;
	}

	public Double getBillpartiAmount() {
		return this.billpartiAmount;
	}

	public void setBillpartiAmount(Double billpartiAmount) {
		this.billpartiAmount = billpartiAmount;
	}

	public Integer getBillpartiQuantity() {
		return this.billpartiQuantity;
	}

	public void setBillpartiQuantity(Integer billpartiQuantity) {
		this.billpartiQuantity = billpartiQuantity;
	}

	public Double getBillpartiTotalamt() {
		return this.billpartiTotalamt;
	}

	public void setBillpartiTotalamt(Double billpartiTotalamt) {
		this.billpartiTotalamt = billpartiTotalamt;
	}

}
