package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TblBillDetails generated by hbm2java
 */
public class TblBillDetails implements java.io.Serializable {

	private String billNos;
	private String partyId;
	private Double billPartitotal;
	private Double billTaxtotal;
	private Double billDiscount;
	private Double billDistotal;
	private Double billRoundoff;
	private Double billFinaltotal;
	private Date billDate;
	private String billPartyId;

	public TblBillDetails() {
	}

	public TblBillDetails(String billNos, String partyId) {
		this.billNos = billNos;
		this.partyId = partyId;
	}

	public TblBillDetails(String billNos, String partyId,
			Double billPartitotal, Double billTaxtotal, Double billDiscount,
			Double billDistotal, Double billRoundoff, Double billFinaltotal,
			Date billDate, String billPartyId) {
		this.billNos = billNos;
		this.partyId = partyId;
		this.billPartitotal = billPartitotal;
		this.billTaxtotal = billTaxtotal;
		this.billDiscount = billDiscount;
		this.billDistotal = billDistotal;
		this.billRoundoff = billRoundoff;
		this.billFinaltotal = billFinaltotal;
		this.billDate = billDate;
		this.billPartyId = billPartyId;
	}

	public String getBillNos() {
		return this.billNos;
	}

	public void setBillNos(String billNos) {
		this.billNos = billNos;
	}

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public Double getBillPartitotal() {
		return this.billPartitotal;
	}

	public void setBillPartitotal(Double billPartitotal) {
		this.billPartitotal = billPartitotal;
	}

	public Double getBillTaxtotal() {
		return this.billTaxtotal;
	}

	public void setBillTaxtotal(Double billTaxtotal) {
		this.billTaxtotal = billTaxtotal;
	}

	public Double getBillDiscount() {
		return this.billDiscount;
	}

	public void setBillDiscount(Double billDiscount) {
		this.billDiscount = billDiscount;
	}

	public Double getBillDistotal() {
		return this.billDistotal;
	}

	public void setBillDistotal(Double billDistotal) {
		this.billDistotal = billDistotal;
	}

	public Double getBillRoundoff() {
		return this.billRoundoff;
	}

	public void setBillRoundoff(Double billRoundoff) {
		this.billRoundoff = billRoundoff;
	}

	public Double getBillFinaltotal() {
		return this.billFinaltotal;
	}

	public void setBillFinaltotal(Double billFinaltotal) {
		this.billFinaltotal = billFinaltotal;
	}

	public Date getBillDate() {
		return this.billDate;
	}

	public void setBillDate(Date billDate) {
		this.billDate = billDate;
	}

	public String getBillPartyId() {
		return this.billPartyId;
	}

	public void setBillPartyId(String billPartyId) {
		this.billPartyId = billPartyId;
	}

}
