package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblBillsubtaxheadDetails generated by hbm2java
 */
public class TblBillsubtaxheadDetails implements java.io.Serializable {

	private Integer billsubtaxId;
	private String billtaxId;
	private String subtaxheadId;
	private Double subtaxheadPercent;
	private Double subtaxheadAmount;

	public TblBillsubtaxheadDetails() {
	}

	public TblBillsubtaxheadDetails(String billtaxId, String subtaxheadId,
			Double subtaxheadPercent, Double subtaxheadAmount) {
		this.billtaxId = billtaxId;
		this.subtaxheadId = subtaxheadId;
		this.subtaxheadPercent = subtaxheadPercent;
		this.subtaxheadAmount = subtaxheadAmount;
	}

	public Integer getBillsubtaxId() {
		return this.billsubtaxId;
	}

	public void setBillsubtaxId(Integer billsubtaxId) {
		this.billsubtaxId = billsubtaxId;
	}

	public String getBilltaxId() {
		return this.billtaxId;
	}

	public void setBilltaxId(String billtaxId) {
		this.billtaxId = billtaxId;
	}

	public String getSubtaxheadId() {
		return this.subtaxheadId;
	}

	public void setSubtaxheadId(String subtaxheadId) {
		this.subtaxheadId = subtaxheadId;
	}

	public Double getSubtaxheadPercent() {
		return this.subtaxheadPercent;
	}

	public void setSubtaxheadPercent(Double subtaxheadPercent) {
		this.subtaxheadPercent = subtaxheadPercent;
	}

	public Double getSubtaxheadAmount() {
		return this.subtaxheadAmount;
	}

	public void setSubtaxheadAmount(Double subtaxheadAmount) {
		this.subtaxheadAmount = subtaxheadAmount;
	}

}
