package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblBilltaxheadDetails generated by hbm2java
 */
public class TblBilltaxheadDetails implements java.io.Serializable {

	private String billtaxId;
	private String billNos;
	private String taxheadId;
	private Double billtaxPercent;
	private Double billtaxAmount;

	public TblBilltaxheadDetails() {
	}

	public TblBilltaxheadDetails(String billtaxId) {
		this.billtaxId = billtaxId;
	}

	public TblBilltaxheadDetails(String billtaxId, String billNos,
			String taxheadId, Double billtaxPercent, Double billtaxAmount) {
		this.billtaxId = billtaxId;
		this.billNos = billNos;
		this.taxheadId = taxheadId;
		this.billtaxPercent = billtaxPercent;
		this.billtaxAmount = billtaxAmount;
	}

	public String getBilltaxId() {
		return this.billtaxId;
	}

	public void setBilltaxId(String billtaxId) {
		this.billtaxId = billtaxId;
	}

	public String getBillNos() {
		return this.billNos;
	}

	public void setBillNos(String billNos) {
		this.billNos = billNos;
	}

	public String getTaxheadId() {
		return this.taxheadId;
	}

	public void setTaxheadId(String taxheadId) {
		this.taxheadId = taxheadId;
	}

	public Double getBilltaxPercent() {
		return this.billtaxPercent;
	}

	public void setBilltaxPercent(Double billtaxPercent) {
		this.billtaxPercent = billtaxPercent;
	}

	public Double getBilltaxAmount() {
		return this.billtaxAmount;
	}

	public void setBilltaxAmount(Double billtaxAmount) {
		this.billtaxAmount = billtaxAmount;
	}

}
