package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblBillreferencesMaster generated by hbm2java
 */
public class TblBillreferencesMaster implements java.io.Serializable {

	private String referenceId;
	private String referenceName;

	public TblBillreferencesMaster() {
	}

	public TblBillreferencesMaster(String referenceId) {
		this.referenceId = referenceId;
	}

	public TblBillreferencesMaster(String referenceId, String referenceName) {
		this.referenceId = referenceId;
		this.referenceName = referenceName;
	}

	public String getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

	public String getReferenceName() {
		return this.referenceName;
	}

	public void setReferenceName(String referenceName) {
		this.referenceName = referenceName;
	}

}
