package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblClientpricelistDetails generated by hbm2java
 */
public class TblClientpricelistDetails implements java.io.Serializable {

	private Integer clientpricedetId;
	private String clientpriceId;
	private String particularsId;
	private double clientpricedetDisc;
	private double clientpricedetAmt;

	public TblClientpricelistDetails() {
	}

	public TblClientpricelistDetails(String clientpriceId,
			String particularsId, double clientpricedetDisc,
			double clientpricedetAmt) {
		this.clientpriceId = clientpriceId;
		this.particularsId = particularsId;
		this.clientpricedetDisc = clientpricedetDisc;
		this.clientpricedetAmt = clientpricedetAmt;
	}

	public Integer getClientpricedetId() {
		return this.clientpricedetId;
	}

	public void setClientpricedetId(Integer clientpricedetId) {
		this.clientpricedetId = clientpricedetId;
	}

	public String getClientpriceId() {
		return this.clientpriceId;
	}

	public void setClientpriceId(String clientpriceId) {
		this.clientpriceId = clientpriceId;
	}

	public String getParticularsId() {
		return this.particularsId;
	}

	public void setParticularsId(String particularsId) {
		this.particularsId = particularsId;
	}

	public double getClientpricedetDisc() {
		return this.clientpricedetDisc;
	}

	public void setClientpricedetDisc(double clientpricedetDisc) {
		this.clientpricedetDisc = clientpricedetDisc;
	}

	public double getClientpricedetAmt() {
		return this.clientpricedetAmt;
	}

	public void setClientpricedetAmt(double clientpricedetAmt) {
		this.clientpricedetAmt = clientpricedetAmt;
	}

}
