package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblCityMaster generated by hbm2java
 */
public class TblCityMaster implements java.io.Serializable {

	private String cityId;
	private TblStateMaster tblStateMaster;
	private String cityName;
	private String cityCode;
	private String status;

	public TblCityMaster() {
	}

	public TblCityMaster(String cityId) {
		this.cityId = cityId;
	}

	public TblCityMaster(String cityId, TblStateMaster tblStateMaster,
			String cityName, String cityCode, String status) {
		this.cityId = cityId;
		this.tblStateMaster = tblStateMaster;
		this.cityName = cityName;
		this.cityCode = cityCode;
		this.status = status;
	}

	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public TblStateMaster getTblStateMaster() {
		return this.tblStateMaster;
	}

	public void setTblStateMaster(TblStateMaster tblStateMaster) {
		this.tblStateMaster = tblStateMaster;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
