package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblParticularsMaster generated by hbm2java
 */
public class TblParticularsMaster implements java.io.Serializable {

	private String particularsId;
	private String particularsName;
	private Long particularsAmt;

	public TblParticularsMaster() {
	}

	public TblParticularsMaster(String particularsId) {
		this.particularsId = particularsId;
	}

	public TblParticularsMaster(String particularsId, String particularsName,
			Long particularsAmt) {
		this.particularsId = particularsId;
		this.particularsName = particularsName;
		this.particularsAmt = particularsAmt;
	}

	public String getParticularsId() {
		return this.particularsId;
	}

	public void setParticularsId(String particularsId) {
		this.particularsId = particularsId;
	}

	public String getParticularsName() {
		return this.particularsName;
	}

	public void setParticularsName(String particularsName) {
		this.particularsName = particularsName;
	}

	public Long getParticularsAmt() {
		return this.particularsAmt;
	}

	public void setParticularsAmt(Long particularsAmt) {
		this.particularsAmt = particularsAmt;
	}

}
