package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblPartyMaster generated by hbm2java
 */
public class TblPartyMaster implements java.io.Serializable {

	private String partyId;
	private TblRoleMaster tblRoleMaster;
	private String partyFname;
	private String partyMname;
	private String partyLname;
	private String cityId;
	private String partyAddress;
	private String partyPinCode;
	private String partyTypeId;
	private String partyStatus;
	private String partyIsInternal;
	private String partyDepTypeId;
	private String empCatId;
	private String partyUsername;
	private String partyPass;
	private String partyEmailFooter;
	private String partyRegDate;
	private String partyEmailid;
	private String partyPhonenos;

	public TblPartyMaster() {
	}

	public TblPartyMaster(String partyId) {
		this.partyId = partyId;
	}

	public TblPartyMaster(String partyId, TblRoleMaster tblRoleMaster,
			String partyFname, String partyMname, String partyLname,
			String cityId, String partyAddress, String partyPinCode,
			String partyTypeId, String partyStatus, String partyIsInternal,
			String partyDepTypeId, String empCatId, String partyUsername,
			String partyPass, String partyEmailFooter, String partyRegDate,
			String partyEmailid, String partyPhonenos) {
		this.partyId = partyId;
		this.tblRoleMaster = tblRoleMaster;
		this.partyFname = partyFname;
		this.partyMname = partyMname;
		this.partyLname = partyLname;
		this.cityId = cityId;
		this.partyAddress = partyAddress;
		this.partyPinCode = partyPinCode;
		this.partyTypeId = partyTypeId;
		this.partyStatus = partyStatus;
		this.partyIsInternal = partyIsInternal;
		this.partyDepTypeId = partyDepTypeId;
		this.empCatId = empCatId;
		this.partyUsername = partyUsername;
		this.partyPass = partyPass;
		this.partyEmailFooter = partyEmailFooter;
		this.partyRegDate = partyRegDate;
		this.partyEmailid = partyEmailid;
		this.partyPhonenos = partyPhonenos;
	}

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	public TblRoleMaster getTblRoleMaster() {
		return this.tblRoleMaster;
	}

	public void setTblRoleMaster(TblRoleMaster tblRoleMaster) {
		this.tblRoleMaster = tblRoleMaster;
	}

	public String getPartyFname() {
		return this.partyFname;
	}

	public void setPartyFname(String partyFname) {
		this.partyFname = partyFname;
	}

	public String getPartyMname() {
		return this.partyMname;
	}

	public void setPartyMname(String partyMname) {
		this.partyMname = partyMname;
	}

	public String getPartyLname() {
		return this.partyLname;
	}

	public void setPartyLname(String partyLname) {
		this.partyLname = partyLname;
	}

	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public String getPartyAddress() {
		return this.partyAddress;
	}

	public void setPartyAddress(String partyAddress) {
		this.partyAddress = partyAddress;
	}

	public String getPartyPinCode() {
		return this.partyPinCode;
	}

	public void setPartyPinCode(String partyPinCode) {
		this.partyPinCode = partyPinCode;
	}

	public String getPartyTypeId() {
		return this.partyTypeId;
	}

	public void setPartyTypeId(String partyTypeId) {
		this.partyTypeId = partyTypeId;
	}

	public String getPartyStatus() {
		return this.partyStatus;
	}

	public void setPartyStatus(String partyStatus) {
		this.partyStatus = partyStatus;
	}

	public String getPartyIsInternal() {
		return this.partyIsInternal;
	}

	public void setPartyIsInternal(String partyIsInternal) {
		this.partyIsInternal = partyIsInternal;
	}

	public String getPartyDepTypeId() {
		return this.partyDepTypeId;
	}

	public void setPartyDepTypeId(String partyDepTypeId) {
		this.partyDepTypeId = partyDepTypeId;
	}

	public String getEmpCatId() {
		return this.empCatId;
	}

	public void setEmpCatId(String empCatId) {
		this.empCatId = empCatId;
	}

	public String getPartyUsername() {
		return this.partyUsername;
	}

	public void setPartyUsername(String partyUsername) {
		this.partyUsername = partyUsername;
	}

	public String getPartyPass() {
		return this.partyPass;
	}

	public void setPartyPass(String partyPass) {
		this.partyPass = partyPass;
	}

	public String getPartyEmailFooter() {
		return this.partyEmailFooter;
	}

	public void setPartyEmailFooter(String partyEmailFooter) {
		this.partyEmailFooter = partyEmailFooter;
	}

	public String getPartyRegDate() {
		return this.partyRegDate;
	}

	public void setPartyRegDate(String partyRegDate) {
		this.partyRegDate = partyRegDate;
	}

	public String getPartyEmailid() {
		return this.partyEmailid;
	}

	public void setPartyEmailid(String partyEmailid) {
		this.partyEmailid = partyEmailid;
	}

	public String getPartyPhonenos() {
		return this.partyPhonenos;
	}

	public void setPartyPhonenos(String partyPhonenos) {
		this.partyPhonenos = partyPhonenos;
	}

}
