package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblPartyemailconfigDetails generated by hbm2java
 */
public class TblPartyemailconfigDetails implements java.io.Serializable {

	private Integer partyemailconfigId;
	private Integer emailconfigId;
	private String partyId;

	public TblPartyemailconfigDetails() {
	}

	public TblPartyemailconfigDetails(Integer emailconfigId, String partyId) {
		this.emailconfigId = emailconfigId;
		this.partyId = partyId;
	}

	public Integer getPartyemailconfigId() {
		return this.partyemailconfigId;
	}

	public void setPartyemailconfigId(Integer partyemailconfigId) {
		this.partyemailconfigId = partyemailconfigId;
	}

	public Integer getEmailconfigId() {
		return this.emailconfigId;
	}

	public void setEmailconfigId(Integer emailconfigId) {
		this.emailconfigId = emailconfigId;
	}

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

}
