package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblPartycommunicationtypeMaster generated by hbm2java
 */
public class TblPartycommunicationtypeMaster implements java.io.Serializable {

	private String partyComTypeId;
	private String partyComTypeName;
	private Set<TblPartycommuncationDetails> tblPartycommuncationDetailses = new HashSet<TblPartycommuncationDetails>(
			0);

	public TblPartycommunicationtypeMaster() {
	}

	public TblPartycommunicationtypeMaster(String partyComTypeId) {
		this.partyComTypeId = partyComTypeId;
	}

	public TblPartycommunicationtypeMaster(String partyComTypeId,
			String partyComTypeName,
			Set<TblPartycommuncationDetails> tblPartycommuncationDetailses) {
		this.partyComTypeId = partyComTypeId;
		this.partyComTypeName = partyComTypeName;
		this.tblPartycommuncationDetailses = tblPartycommuncationDetailses;
	}

	public String getPartyComTypeId() {
		return this.partyComTypeId;
	}

	public void setPartyComTypeId(String partyComTypeId) {
		this.partyComTypeId = partyComTypeId;
	}

	public String getPartyComTypeName() {
		return this.partyComTypeName;
	}

	public void setPartyComTypeName(String partyComTypeName) {
		this.partyComTypeName = partyComTypeName;
	}

	public Set<TblPartycommuncationDetails> getTblPartycommuncationDetailses() {
		return this.tblPartycommuncationDetailses;
	}

	public void setTblPartycommuncationDetailses(
			Set<TblPartycommuncationDetails> tblPartycommuncationDetailses) {
		this.tblPartycommuncationDetailses = tblPartycommuncationDetailses;
	}

}
