package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblPartydepartmenttypeMaster generated by hbm2java
 */
public class TblPartydepartmenttypeMaster implements java.io.Serializable {

	private String partyDepTypeId;
	private String partyDepTypeName;

	public TblPartydepartmenttypeMaster() {
	}

	public TblPartydepartmenttypeMaster(String partyDepTypeId) {
		this.partyDepTypeId = partyDepTypeId;
	}

	public TblPartydepartmenttypeMaster(String partyDepTypeId,
			String partyDepTypeName) {
		this.partyDepTypeId = partyDepTypeId;
		this.partyDepTypeName = partyDepTypeName;
	}

	public String getPartyDepTypeId() {
		return this.partyDepTypeId;
	}

	public void setPartyDepTypeId(String partyDepTypeId) {
		this.partyDepTypeId = partyDepTypeId;
	}

	public String getPartyDepTypeName() {
		return this.partyDepTypeName;
	}

	public void setPartyDepTypeName(String partyDepTypeName) {
		this.partyDepTypeName = partyDepTypeName;
	}

}
