package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblPartycommuncationDetails generated by hbm2java
 */
public class TblPartycommuncationDetails implements java.io.Serializable {

	private String partyComId;
	private TblPartycommunicationtypeMaster tblPartycommunicationtypeMaster;
	private String partyComInfostr;
	private String partyComStatus;
	private String partyId;

	public TblPartycommuncationDetails() {
	}

	public TblPartycommuncationDetails(String partyComId) {
		this.partyComId = partyComId;
	}

	public TblPartycommuncationDetails(String partyComId,
			TblPartycommunicationtypeMaster tblPartycommunicationtypeMaster,
			String partyComInfostr, String partyComStatus, String partyId) {
		this.partyComId = partyComId;
		this.tblPartycommunicationtypeMaster = tblPartycommunicationtypeMaster;
		this.partyComInfostr = partyComInfostr;
		this.partyComStatus = partyComStatus;
		this.partyId = partyId;
	}

	public String getPartyComId() {
		return this.partyComId;
	}

	public void setPartyComId(String partyComId) {
		this.partyComId = partyComId;
	}

	public TblPartycommunicationtypeMaster getTblPartycommunicationtypeMaster() {
		return this.tblPartycommunicationtypeMaster;
	}

	public void setTblPartycommunicationtypeMaster(
			TblPartycommunicationtypeMaster tblPartycommunicationtypeMaster) {
		this.tblPartycommunicationtypeMaster = tblPartycommunicationtypeMaster;
	}

	public String getPartyComInfostr() {
		return this.partyComInfostr;
	}

	public void setPartyComInfostr(String partyComInfostr) {
		this.partyComInfostr = partyComInfostr;
	}

	public String getPartyComStatus() {
		return this.partyComStatus;
	}

	public void setPartyComStatus(String partyComStatus) {
		this.partyComStatus = partyComStatus;
	}

	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

}
