package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblRoledetailMaster generated by hbm2java
 */
public class TblRoledetailMaster implements java.io.Serializable {

	private Integer roledetailId;
	private TblRoleMaster tblRoleMaster;
	private String roledetailModule;
	private String roledetailAccess;
	private String roledetailAdd;
	private String roledetailEdit;
	private String roledetailDelete;

	public TblRoledetailMaster() {
	}

	public TblRoledetailMaster(TblRoleMaster tblRoleMaster,
			String roledetailModule, String roledetailAccess,
			String roledetailAdd, String roledetailEdit, String roledetailDelete) {
		this.tblRoleMaster = tblRoleMaster;
		this.roledetailModule = roledetailModule;
		this.roledetailAccess = roledetailAccess;
		this.roledetailAdd = roledetailAdd;
		this.roledetailEdit = roledetailEdit;
		this.roledetailDelete = roledetailDelete;
	}

	public Integer getRoledetailId() {
		return this.roledetailId;
	}

	public void setRoledetailId(Integer roledetailId) {
		this.roledetailId = roledetailId;
	}

	public TblRoleMaster getTblRoleMaster() {
		return this.tblRoleMaster;
	}

	public void setTblRoleMaster(TblRoleMaster tblRoleMaster) {
		this.tblRoleMaster = tblRoleMaster;
	}

	public String getRoledetailModule() {
		return this.roledetailModule;
	}

	public void setRoledetailModule(String roledetailModule) {
		this.roledetailModule = roledetailModule;
	}

	public String getRoledetailAccess() {
		return this.roledetailAccess;
	}

	public void setRoledetailAccess(String roledetailAccess) {
		this.roledetailAccess = roledetailAccess;
	}

	public String getRoledetailAdd() {
		return this.roledetailAdd;
	}

	public void setRoledetailAdd(String roledetailAdd) {
		this.roledetailAdd = roledetailAdd;
	}

	public String getRoledetailEdit() {
		return this.roledetailEdit;
	}

	public void setRoledetailEdit(String roledetailEdit) {
		this.roledetailEdit = roledetailEdit;
	}

	public String getRoledetailDelete() {
		return this.roledetailDelete;
	}

	public void setRoledetailDelete(String roledetailDelete) {
		this.roledetailDelete = roledetailDelete;
	}

}
