package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblSubtaxheadMaster generated by hbm2java
 */
public class TblSubtaxheadMaster implements java.io.Serializable {

	private String subtaxheadId;
	private String taxheadId;
	private String subtaxheadName;
	private String subtaxheadYear;
	private Double subtaxheadPercent;
	private String subtaxheadStatus;

	public TblSubtaxheadMaster() {
	}

	public TblSubtaxheadMaster(String subtaxheadId) {
		this.subtaxheadId = subtaxheadId;
	}

	public TblSubtaxheadMaster(String subtaxheadId, String taxheadId,
			String subtaxheadName, String subtaxheadYear,
			Double subtaxheadPercent, String subtaxheadStatus) {
		this.subtaxheadId = subtaxheadId;
		this.taxheadId = taxheadId;
		this.subtaxheadName = subtaxheadName;
		this.subtaxheadYear = subtaxheadYear;
		this.subtaxheadPercent = subtaxheadPercent;
		this.subtaxheadStatus = subtaxheadStatus;
	}

	public String getSubtaxheadId() {
		return this.subtaxheadId;
	}

	public void setSubtaxheadId(String subtaxheadId) {
		this.subtaxheadId = subtaxheadId;
	}

	public String getTaxheadId() {
		return this.taxheadId;
	}

	public void setTaxheadId(String taxheadId) {
		this.taxheadId = taxheadId;
	}

	public String getSubtaxheadName() {
		return this.subtaxheadName;
	}

	public void setSubtaxheadName(String subtaxheadName) {
		this.subtaxheadName = subtaxheadName;
	}

	public String getSubtaxheadYear() {
		return this.subtaxheadYear;
	}

	public void setSubtaxheadYear(String subtaxheadYear) {
		this.subtaxheadYear = subtaxheadYear;
	}

	public Double getSubtaxheadPercent() {
		return this.subtaxheadPercent;
	}

	public void setSubtaxheadPercent(Double subtaxheadPercent) {
		this.subtaxheadPercent = subtaxheadPercent;
	}

	public String getSubtaxheadStatus() {
		return this.subtaxheadStatus;
	}

	public void setSubtaxheadStatus(String subtaxheadStatus) {
		this.subtaxheadStatus = subtaxheadStatus;
	}

}
