package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TblYearMaster generated by hbm2java
 */
public class TblYearMaster implements java.io.Serializable {

	private String yearName;
	private String yearAliasName;
	private Date yearFromdate;
	private Date yearTodate;

	public TblYearMaster() {
	}

	public TblYearMaster(String yearName) {
		this.yearName = yearName;
	}

	public TblYearMaster(String yearName, String yearAliasName,
			Date yearFromdate, Date yearTodate) {
		this.yearName = yearName;
		this.yearAliasName = yearAliasName;
		this.yearFromdate = yearFromdate;
		this.yearTodate = yearTodate;
	}

	public String getYearName() {
		return this.yearName;
	}

	public void setYearName(String yearName) {
		this.yearName = yearName;
	}

	public String getYearAliasName() {
		return this.yearAliasName;
	}

	public void setYearAliasName(String yearAliasName) {
		this.yearAliasName = yearAliasName;
	}

	public Date getYearFromdate() {
		return this.yearFromdate;
	}

	public void setYearFromdate(Date yearFromdate) {
		this.yearFromdate = yearFromdate;
	}

	public Date getYearTodate() {
		return this.yearTodate;
	}

	public void setYearTodate(Date yearTodate) {
		this.yearTodate = yearTodate;
	}

}
