package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * VwClientpricelistDetails generated by hbm2java
 */
public class VwClientpricelistDetails implements java.io.Serializable {

	private VwClientpricelistDetailsId id;

	public VwClientpricelistDetails() {
	}

	public VwClientpricelistDetails(VwClientpricelistDetailsId id) {
		this.id = id;
	}

	public VwClientpricelistDetailsId getId() {
		return this.id;
	}

	public void setId(VwClientpricelistDetailsId id) {
		this.id = id;
	}

}
