package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * VwTaxheadAcyear generated by hbm2java
 */
public class VwTaxheadAcyear implements java.io.Serializable {

	private VwTaxheadAcyearId id;

	public VwTaxheadAcyear() {
	}

	public VwTaxheadAcyear(VwTaxheadAcyearId id) {
		this.id = id;
	}

	public VwTaxheadAcyearId getId() {
		return this.id;
	}

	public void setId(VwTaxheadAcyearId id) {
		this.id = id;
	}

}
