package com.subodh;

// Generated Jan 4, 2014 4:28:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VwTaxheadAcyearId generated by hbm2java
 */
public class VwTaxheadAcyearId implements java.io.Serializable {

	private String acyearId;
	private String acyearName;
	private String acyearText;
	private Date acyearFromdate;
	private Date acyearTodate;
	private String acyearCurrentyear;
	private String taxheadId;
	private String taxheadName;
	private double taxheadPercent;
	private String taxheadYear;
	private String taxheadStatus;

	public VwTaxheadAcyearId() {
	}

	public VwTaxheadAcyearId(String acyearId, String taxheadId,
			String taxheadName, double taxheadPercent, String taxheadYear,
			String taxheadStatus) {
		this.acyearId = acyearId;
		this.taxheadId = taxheadId;
		this.taxheadName = taxheadName;
		this.taxheadPercent = taxheadPercent;
		this.taxheadYear = taxheadYear;
		this.taxheadStatus = taxheadStatus;
	}

	public VwTaxheadAcyearId(String acyearId, String acyearName,
			String acyearText, Date acyearFromdate, Date acyearTodate,
			String acyearCurrentyear, String taxheadId, String taxheadName,
			double taxheadPercent, String taxheadYear, String taxheadStatus) {
		this.acyearId = acyearId;
		this.acyearName = acyearName;
		this.acyearText = acyearText;
		this.acyearFromdate = acyearFromdate;
		this.acyearTodate = acyearTodate;
		this.acyearCurrentyear = acyearCurrentyear;
		this.taxheadId = taxheadId;
		this.taxheadName = taxheadName;
		this.taxheadPercent = taxheadPercent;
		this.taxheadYear = taxheadYear;
		this.taxheadStatus = taxheadStatus;
	}

	public String getAcyearId() {
		return this.acyearId;
	}

	public void setAcyearId(String acyearId) {
		this.acyearId = acyearId;
	}

	public String getAcyearName() {
		return this.acyearName;
	}

	public void setAcyearName(String acyearName) {
		this.acyearName = acyearName;
	}

	public String getAcyearText() {
		return this.acyearText;
	}

	public void setAcyearText(String acyearText) {
		this.acyearText = acyearText;
	}

	public Date getAcyearFromdate() {
		return this.acyearFromdate;
	}

	public void setAcyearFromdate(Date acyearFromdate) {
		this.acyearFromdate = acyearFromdate;
	}

	public Date getAcyearTodate() {
		return this.acyearTodate;
	}

	public void setAcyearTodate(Date acyearTodate) {
		this.acyearTodate = acyearTodate;
	}

	public String getAcyearCurrentyear() {
		return this.acyearCurrentyear;
	}

	public void setAcyearCurrentyear(String acyearCurrentyear) {
		this.acyearCurrentyear = acyearCurrentyear;
	}

	public String getTaxheadId() {
		return this.taxheadId;
	}

	public void setTaxheadId(String taxheadId) {
		this.taxheadId = taxheadId;
	}

	public String getTaxheadName() {
		return this.taxheadName;
	}

	public void setTaxheadName(String taxheadName) {
		this.taxheadName = taxheadName;
	}

	public double getTaxheadPercent() {
		return this.taxheadPercent;
	}

	public void setTaxheadPercent(double taxheadPercent) {
		this.taxheadPercent = taxheadPercent;
	}

	public String getTaxheadYear() {
		return this.taxheadYear;
	}

	public void setTaxheadYear(String taxheadYear) {
		this.taxheadYear = taxheadYear;
	}

	public String getTaxheadStatus() {
		return this.taxheadStatus;
	}

	public void setTaxheadStatus(String taxheadStatus) {
		this.taxheadStatus = taxheadStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwTaxheadAcyearId))
			return false;
		VwTaxheadAcyearId castOther = (VwTaxheadAcyearId) other;

		return ((this.getAcyearId() == castOther.getAcyearId()) || (this
				.getAcyearId() != null && castOther.getAcyearId() != null && this
				.getAcyearId().equals(castOther.getAcyearId())))
				&& ((this.getAcyearName() == castOther.getAcyearName()) || (this
						.getAcyearName() != null
						&& castOther.getAcyearName() != null && this
						.getAcyearName().equals(castOther.getAcyearName())))
				&& ((this.getAcyearText() == castOther.getAcyearText()) || (this
						.getAcyearText() != null
						&& castOther.getAcyearText() != null && this
						.getAcyearText().equals(castOther.getAcyearText())))
				&& ((this.getAcyearFromdate() == castOther.getAcyearFromdate()) || (this
						.getAcyearFromdate() != null
						&& castOther.getAcyearFromdate() != null && this
						.getAcyearFromdate().equals(
								castOther.getAcyearFromdate())))
				&& ((this.getAcyearTodate() == castOther.getAcyearTodate()) || (this
						.getAcyearTodate() != null
						&& castOther.getAcyearTodate() != null && this
						.getAcyearTodate().equals(castOther.getAcyearTodate())))
				&& ((this.getAcyearCurrentyear() == castOther
						.getAcyearCurrentyear()) || (this
						.getAcyearCurrentyear() != null
						&& castOther.getAcyearCurrentyear() != null && this
						.getAcyearCurrentyear().equals(
								castOther.getAcyearCurrentyear())))
				&& ((this.getTaxheadId() == castOther.getTaxheadId()) || (this
						.getTaxheadId() != null
						&& castOther.getTaxheadId() != null && this
						.getTaxheadId().equals(castOther.getTaxheadId())))
				&& ((this.getTaxheadName() == castOther.getTaxheadName()) || (this
						.getTaxheadName() != null
						&& castOther.getTaxheadName() != null && this
						.getTaxheadName().equals(castOther.getTaxheadName())))
				&& (this.getTaxheadPercent() == castOther.getTaxheadPercent())
				&& ((this.getTaxheadYear() == castOther.getTaxheadYear()) || (this
						.getTaxheadYear() != null
						&& castOther.getTaxheadYear() != null && this
						.getTaxheadYear().equals(castOther.getTaxheadYear())))
				&& ((this.getTaxheadStatus() == castOther.getTaxheadStatus()) || (this
						.getTaxheadStatus() != null
						&& castOther.getTaxheadStatus() != null && this
						.getTaxheadStatus()
						.equals(castOther.getTaxheadStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAcyearId() == null ? 0 : this.getAcyearId().hashCode());
		result = 37
				* result
				+ (getAcyearName() == null ? 0 : this.getAcyearName()
						.hashCode());
		result = 37
				* result
				+ (getAcyearText() == null ? 0 : this.getAcyearText()
						.hashCode());
		result = 37
				* result
				+ (getAcyearFromdate() == null ? 0 : this.getAcyearFromdate()
						.hashCode());
		result = 37
				* result
				+ (getAcyearTodate() == null ? 0 : this.getAcyearTodate()
						.hashCode());
		result = 37
				* result
				+ (getAcyearCurrentyear() == null ? 0 : this
						.getAcyearCurrentyear().hashCode());
		result = 37 * result
				+ (getTaxheadId() == null ? 0 : this.getTaxheadId().hashCode());
		result = 37
				* result
				+ (getTaxheadName() == null ? 0 : this.getTaxheadName()
						.hashCode());
		result = 37 * result + (int) this.getTaxheadPercent();
		result = 37
				* result
				+ (getTaxheadYear() == null ? 0 : this.getTaxheadYear()
						.hashCode());
		result = 37
				* result
				+ (getTaxheadStatus() == null ? 0 : this.getTaxheadStatus()
						.hashCode());
		return result;
	}

}
